# 反作弊插件配置
language: zh_cn

settings:
  # 调试模式
  debug: false
  # 踢出广播
  broadcast-kick: true
  
  # 检测开关
  movement:
    enabled: true # 移动检测开关
    max-horizontal-speed: 0.90 # 横向速度检测
    max-vertical-speed: 0.45 # 垂直速度检测
    check-jump-boost: true
    check-ground-speed: true
  
  rotation:
    enabled: true # 视角检测开关
    max-angle-change: 1350
    check-interval: 15 # 毫秒
    check-pitch: true
  
  clicks:
    enabled: true # 点击检测开关
    max-cps: 18 # 每秒最大点击次数
    check-interval: 1 # 检测间隔(秒)
    violations-to-kick: 2 # 触发多少次后踢出
  
  flight:
    enabled: true # 飞行检测开关
    max-air-time: 80 # 最大空中时间 (tick)，20 tick = 1秒
    ignore-water: true # 忽略水中飞行检测
    ignore-climbables: true # 忽略攀爬物飞行检测
  
  elytra:
    enabled: true # 鞘翅检测开关
    max-horizontal-speed: 2.0 # 水平速度阈值
    max-vertical-speed: 1.5   # 垂直速度阈值
    landing-buffer: 0.5 # 落地缓冲时间（秒）
    buffer-multiplier: 1.5 # 缓冲期速度乘数
  
  # 违规处理设置
  violations:
    max-violations: 10
    violation-expire: 60 # 分钟
    
    # 自动封禁配置
    auto-ban:
      enabled: true
      kicks-before-ban: 3 # 被踢出多少次后封禁
  
  # 日志记录
  log-violations: true

# 白名单配置
whitelist:
  players: []
  worlds:
    - "creative_world"
    - "minigame_arena"
  
  # 忽略的权限节点
  bypass-permissions:
    - "anticheat.bypass.speed"
    - "anticheat.bypass.rotation"
    - "anticheat.bypass.clicks"
    - "anticheat.bypass.flight"
    - "anticheat.bypass.elytra"
