# 语言设置
language: zh_cn

# 通用设置
settings:
  debug: false
  violations:
    max-violations: 10
    auto-ban:
      enabled: true
      kicks-before-ban: 3

# 移动检测
movement:
  max-horizontal-speed: 0.90
  max-vertical-speed: 114514.00

# 鞘翅专用阈值
elytra:
  max-horizontal-speed: 99999.00
  max-vertical-speed: 99999.00

# 视角检测
rotation:
  max-angle-change: 30.0
  check-interval: 50

# 点击检测
clicks:
  enabled: true
  max-cps: 17
  check-interval: 5
  violations-to-kick: 3

# 飞行检测
flight:
  enabled: true
  max-air-time: 100 #这里是tick值，20tick=1秒

# 白名单
whitelist:
  worlds:
    - world_creative
    - world_minigames
  players:
    - "" # UUID
  bypass-permissions:
    - "anticheat.bypass"
    - "staff.*"
