# 反作弊插件配置
language: cn  # 可选值: en, zh_CN, es, fr 等

settings:
  # 移动检测设置
  movement:
    max-horizontal-speed: 0.62
    max-vertical-speed: 0.63
    check-jump-boost: true
    check-ground-speed: true
  
  # 视角检测设置
  rotation:
    max-angle-change: 900.0
    check-interval: 50 # 毫秒
    check-pitch: true
  
  # 点击检测设置
  clicks:
    enabled: true
    max-cps: 16 # 每秒最大点击次数
    check-interval: 1 # 检测间隔(秒)
    violations-to-kick: 2 # 触发多少次后踢出
  
  # 违规处理设置
  violations:
    max-violations: 10
    violation-expire: 60 # 分钟
    
    # 自动封禁配置
    auto-ban:
      enabled: true
      kicks-before-ban: 3 # 被踢出多少次后封禁
  
  # 调试模式
  debug: false
  log-violations: true

# 白名单配置
whitelist:
  players: []
  worlds:
    - "creative_world"
    - "minigame_arena"
  
  # 忽略的权限节点
  bypass-permissions:
    - "anticheat.bypass.speed"
    - "anticheat.bypass.rotation"
    - "anticheat.bypass.clicks"
