name: TRAntiCheat
main: com.tr.anticheat.AntiCheatPlugin
version: 1.0.6
api-version: 1.16
description: Advanced anti-cheat system for Minecraft servers
author: Traveler114514
website: https://github.com/Traveler114514

commands:
  traban:
    description: Ban a player using the custom ban system
    usage: /traban <player> <reason>
    permission: anticheat.traban
    permission-message: "&c你没有权限使用这个命令!"
  
  traunban:
    description: Unban a player from the custom ban system
    usage: /traunban <player> [reason]
    permission: anticheat.traunban
    permission-message: "&c你没有权限使用这个命令!"

permissions:
  anticheat.traban:
    description: Allows banning players using the custom ban system
    default: op
  anticheat.traunban:
    description: Allows unbanning players from the custom ban system
    default: op
  anticheat.admin:
    description: Access to anti-cheat admin features
    default: op
  anticheat.bypass:
    description: Bypass anti-cheat detections
    default: false
